targets:
  $default:
    builders:
      flutter_hook_form:
        enabled: true
        generate_for:
          - lib/**.dart

builders:
  form_schema:
    import: "package:flutter_hook_form/builder/builder.dart"
    builder_factories: ["formSchemaBuilder"]
    build_extensions: { ".dart": [".schema.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
