name: flutter_hook_form
description: "A Flutter package that provides a hook to manage form fields."
version: 0.0.2
repository: https://github.com/kylianSalomon/flutter_hook_form
issue_tracker: https://github.com/kylianSalomon/flutter_hook_form/issues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.0
  cross_file: ^0.3.4+2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  mime: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
